Repository OpenSourcePolitics/decidim-app, pull requests merged in 2024-09, with the labels that each got.

#585 feat: Add simple proposal gem
  Gemfile
  Gemfile.lock
  app/controllers/concerns/decidim/simple_proposal/proposals_controller_override.rb
  config/locales/en.yml
  config/locales/fr.yml
  db/migrate/20240904084430_add_deleted_at_to_proposals.decidim_simple_proposal.rb
  db/schema.rb
  spec/controllers/decidim/proposals/proposals_controller_spec.rb
  spec/system/proposals_spec.rb
Labels: type: module, status: testing, release: v2.4

#584 Fix reflected XSS on meetings versions
  OVERLOADS.md
  app/cells/decidim/version_cell.rb
  spec/cells/decidim/version_cell_spec.rb
Labels: release: v2.4

#568 feat: export authorization metadata to user extended data
  .env-example
  app/jobs/authorization_data_to_user_data_job.rb
  app/services/decidim/authorization_data_to_user_data_service.rb
  config/application.rb
  config/secrets.yml
  lib/extends/models/decidim/authorization_extends.rb
  lib/extends/models/decidim/budgets/project_extends.rb
  lib/tasks/authorizations.rake
Labels: priority: high, type: feature
