Repository OpenSourcePolitics/decidim-app, pull requests merged in 2024-11, with the labels that each got.

#605 feat: Add Sendethics possibility to the sms gateway
  .env-example
  app/services/decidim/sms_gateway_service.rb
  config/secrets.yml
  spec/services/decidim/sms_gateway_service_spec.rb
Labels: release: v2.5

#611 Decrypt private body extra fields
  app/jobs/private_body_decrypt_job.rb
  lib/tasks/set_decrypted_private_body.rake
  spec/jobs/private_body_decrypt_job_spec.rb
  spec/lib/tasks/decidim_app/set_decrypted_private_body_task_spec.rb
Labels: release: v2.5, release: v2.5.0

#622 backport: remove sentry
  .env-example
  .overloads
  Gemfile
  Gemfile.lock
  app.json
  app/views/layouts/decidim/_head_extra.html.erb
  config/initializers/sentry.rb
  config/secrets.yml
  lib/decidim_app/sentry_setup.rb
  spec/lib/decidim_app/sentry_setup_spec.rb
Labels: priority: high, type: fix, release: v2.5

#624 Backport self hosted cdn
  app/packs/src/decidim/decidim_awesome/admin/custom_fields_builder.js
  app/packs/src/decidim/decidim_awesome/forms/custom_fields_renderer.js
  config/initializers/awesome_defaults.rb
Labels: priority: high, type: fix, release: v2.5

#621 Fix/missing image in survey question
  app/packs/src/decidim/decidim_awesome/editors/editor.js
  app/packs/src/decidim/editor.js
  spec/system/admin/admin_manages_survey_question_with_image_spec.rb
  spec/system/admin/admin_updates_question_in_questionnaire_templates_spec.rb
Labels: type: bug, priority: medium, status: testing, release: v2.5

#618 Fix/questions order in survey export
  lib/extends/lib/decidim/forms/user_answers_serializer_extend.rb
  spec/serializers/decidim/forms/user_answers_serializer_spec.rb
Labels: priority: medium, type: fix, release: v2.5

#625 Bump: Guest meeting registration module
  Gemfile
  Gemfile.lock
Labels: priority: medium, type: fix, status: testing, release: v2.5

#608 Feat/add decypted private body to extra fields
  .rubocop_rails.yml
  app/jobs/private_body_decrypt_job.rb
  config/application.rb
  db/migrate/20241011092707_add_decrypted_private_body_to_proposal_extra_field.rb
  db/schema.rb
  lib/extends/models/decidim/decidim_awesome/proposal_extra_field_extends.rb
  lib/tasks/set_decrypted_private_body.rake
  spec/jobs/private_body_decrypt_job_spec.rb
  spec/lib/tasks/decidim_app/set_decrypted_private_body_task_spec.rb
  spec/models/decidim/decidim_awesome/proposal_extra_field_spec.rb
Labels: release: v2.5

#612 feat: Clear minio s3 bucket
  app/jobs/active_storage_clear_orphans_job.rb
  config/sidekiq.yml
  config/storage.yml
  docker-compose.local.yml
  lib/tasks/active_storage.rake
Labels: release: v2.5, release: v2.5.0

#626 Fix custom sort for processes missing date
  app/controllers/decidim/assemblies/assemblies_controller.rb
  app/controllers/decidim/participatory_processes/participatory_processes_controller.rb
  spec/controllers/assemblies_controller_spec.rb
  spec/controllers/participatory_processes_controller_spec.rb
Labels: priority: high, type: fix, status: testing, release: v2.5

#635 bump: Homepage Interactive Map - Geocoding Issues
  Gemfile.lock
Labels: release: v2.5.1

#633 feat: Addition of the module emitter
  Gemfile
  Gemfile.lock
  app/views/decidim/participatory_processes/admin/participatory_processes/_form.html.erb
  config/i18n-tasks.yml
  config/initializers/half_signup.rb
  db/migrate/20241118114335_add_emitter_to_decidim_participatory_process.decidim_emitter.rb
  db/schema.rb
  spec/factories.rb
  spec/shared/manage_processes_examples.rb
  spec/shared/participatory_process_administration_by_admin_shared_context.rb
  spec/shared/participatory_process_administration_shared_context.rb
  spec/system/admin/admin_manages_participatory_processes_spec.rb
  spec/system/participatory_processes_spec.rb
Labels: release: v2.5.1

#631 Fix/backport decidim awesome slowness on proposals index page
  .env-example
  config/environments/development.rb
  config/initializers/decidim_awesome.rb
  config/secrets.yml
  spec/models/decidim/decidim_awesome/proposal_extra_field_spec.rb
Labels: release: v2.5.1

#632 backport: Addition of sortable scopes using drag and drop
  app/commands/admin/reorder_scopes.rb
  app/forms/decidim/user_interest_scope_form.rb
  app/forms/decidim/user_interests_form.rb
  app/helpers/concerns/decidim/simple_proposal/scopes_helper_override.rb
  app/packs/entrypoints/application.js
  app/packs/entrypoints/decidim_custom_scopes.scss
  app/packs/src/decidim/admin/reorder_scopes.js
  app/packs/stylesheets/decidim/scopes/_scopes-custom.scss
  app/views/decidim/admin/scopes/index.html.erb
  config/application.rb
  config/locales/en.yml
  config/locales/fr.yml
  db/migrate/20240412112810_add_weight_to_scopes.rb
  db/schema.rb
  lib/extends/controllers/decidim/admin/scopes_controller_extends.rb
  lib/extends/controllers/decidim/scopes_controller_extends.rb
  lib/extends/helpers/decidim/check_boxes_tree_helper_extends.rb
  spec/helpers/decidim/check_boxes_tree_helper_spec.rb
  spec/system/admin_manages_organization_scopes_spec.rb
Labels: release: v2.5.1

#627 feat: Allow to choose notification settings when attachment added
  app/forms/decidim/admin/attachment_form.rb
  app/views/decidim/admin/attachments/_form.html.erb
  config/application.rb
  config/locales/en.yml
  config/locales/fr.yml
  lib/extends/commands/decidim/admin/create_attachment_extends.rb
  spec/commands/decidim/admin/create_attachment_spec.rb
Labels: release: v2.5.1

#638 fix: Map not displaying when refreshing
  app/views/decidim/proposals/proposals/index.html.erb
Labels: release: v2.5.1
