Repository OpenSourcePolitics/decidim-app, pull requests merged in 2024-07, with the labels that each got.

#561 Fix/sk email locales
  .env-example
  config/locales/sk.decidim-core.yml
Labels: release: v2.3

#537 Fix/deleting follows of deleted private users
  config/application.rb
  lib/extends/commands/decidim/admin/destroy_participatory_space_private_user_extends.rb
  spec/commands/decidim/admin/destroy_participatory_space_private_user_spec.rb
  spec/spec_helper.rb
  spec/system/admin/update_initiative_spec.rb
Labels: release: v2.3, priority: low, type: fix, status: testing

#554 feat: Optimize local docker build
  Dockerfile.local
  Makefile
  docker-compose.local.yml
Labels: type: enhancement, release: v2.3, priority: low, status: ready for staging

#548 Bump Term-Customizer
  Gemfile.lock
  app/packs/entrypoints/decidim_tc.scss
  app/packs/stylesheets/decidim/decidim_application.scss
  app/packs/stylesheets/decidim/modules/term_customizer.scss
  app/views/decidim/term_customizer/admin/add_translations/index.html.erb
  config/assets.rb
  config/i18n-tasks.yml
  yarn.lock
Labels: release: v2.3, priority: medium, type: fix

#527 feat: Module anonymous proposals
  Gemfile
  Gemfile.lock
  lib/tasks/decidim_app.rake
Labels: release: v2.3, priority: medium, type: module, status: testing

#564 Release 2.3.0
  .env-example
  Dockerfile.local
  Gemfile
  Gemfile.lock
  Makefile
  app/packs/entrypoints/decidim_tc.scss
  app/packs/images/icon-circle-check.svg
  app/packs/images/icon-cloud.svg
  app/packs/images/icon-key.svg
  app/packs/images/icon-lock-locked.svg
  app/packs/images/icon-people.svg
  app/packs/images/icon-person.svg
  app/packs/images/icon-shield.svg
  app/packs/images/icon-verified-badge.svg
  app/packs/stylesheets/decidim/decidim_application.scss
  app/packs/stylesheets/decidim/modules/term_customizer.scss
  app/views/decidim/term_customizer/admin/add_translations/index.html.erb
  config/application.rb
  config/assets.rb
  config/i18n-tasks.yml
  config/initializers/omniauth_openid_connect.rb
  config/locales/en.yml
  config/locales/fr.yml
  config/locales/sk.decidim-core.yml
  config/secrets.yml
  docker-compose.local.yml
  lib/decidim_app/omniauth/utils.rb
  lib/extends/commands/decidim/admin/destroy_participatory_space_private_user_extends.rb
  lib/migrations_fixer.rb
  lib/tasks/decidim_app.rake
  lib/tasks/migrate.rake
  spec/commands/decidim/admin/destroy_participatory_space_private_user_spec.rb
  spec/lib/migrations_fixer_spec.rb
  spec/spec_helper.rb
  spec/system/admin/update_initiative_spec.rb
  yarn.lock
Labels: release: v2.3, priority: high, status: testing
