Repository OpenSourcePolitics/decidim-app, pull requests merged in 2024-05, with the labels that each got.

#528 Release v2.1.0 decidim-app
  .env-example
  .github/workflows/ci_cd.yml
  Gemfile
  Gemfile.lock
  app/views/decidim/account/show.html.erb
  app/views/decidim/proposals/collaborative_drafts/_edit_form_fields.html.erb
  config/i18n-tasks.yml
  config/initializers/decidim.rb
  config/initializers/extends.rb
  config/initializers/friendly_signup.rb
  config/locales/en.yml
  config/locales/fr.yml
  db/migrate/20240305083819_add_colors_to_decidim_categories.decidim_category_enhanced.rb
  db/migrate/20240404060339_add_category_budget_rules_to_decidim_budgets.decidim_budget_category_voting.rb
  db/schema.rb
  lib/extends/lib/decidim/forms/user_answers_serializer_extend.rb
  lib/extends/models/decidim/budgets/project_extend.rb
  package-lock.json
  spec/commands/decidim/create_registration_spec.rb
  spec/lib/decidim_app/k8s/organization_exporter_spec.rb
  spec/models/decidim/budgets/project_spec.rb
  spec/serializers/decidim/forms/user_answers_serializer_spec.rb
  spec/services/decidim/proposals/proposal_serializer_spec.rb
  spec/system/account_spec.rb
  spec/system/extra_user_fields/account_spec.rb
  spec/wicked_pdf_spec.rb
  yarn.lock
Labels: v2.1.0

#531 fix: Remove unused Active Storage Migrator
  lib/active_storage/migrator.rb
  lib/tasks/scaleway.rake
  spec/lib/active_storage/migrator_spec.rb
  spec/lib/tasks/scaleway/storage/migrate_from_local_task_spec.rb
Labels: enhancement

#532 feat: Add module budgets_importer to Marseille
  Gemfile
  Gemfile.lock
  config/i18n-tasks.yml
  config/locales/fr.yml
  spec/commands/decidim/budgets_importer/admin/import_project_spec.rb
  spec/spec_helper.rb
Labels: high priority, add module

#538 Fix: Change half_sign_up module branch
  Gemfile
  Gemfile.lock
Labels: priority: high, type: change, status: testing

#539 Fix: Bump Decidim Awesome
  Gemfile
  Gemfile.lock
Labels: priority: high, type: fix, status: ready for production

#543 fix: Marseille : Rescue DB migrate error
  lib/tasks/decidim_app.rake
Labels: priority: medium, type: fix

#542 fix: Rescue DB migrate error
  lib/tasks/decidim_app.rake
Labels: priority: medium, type: fix
